FROM public.ecr.aws/amazonlinux/amazonlinux:2023

# Install Dependencies
RUN dnf update -y && \
    dnf install -y wget zip gzip xz tar && \
    dnf clean all && \
    rm -rf /var/cache/yum

# Install Node Exporter
RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-arm64.tar.gz && \
    tar -xvzf node_exporter-1.8.2.linux-arm64.tar.gz && \
    mv node_exporter-1.8.2.linux-arm64/node_exporter /usr/local/bin/node_exporter

# Install Promtail
RUN wget https://github.com/grafana/loki/releases/download/v2.9.9/promtail-linux-arm64.zip && \
    unzip promtail-linux-arm64.zip && \
    mv promtail-linux-arm64 /usr/local/bin/promtail

# Install Logcli
RUN wget https://github.com/grafana/loki/releases/download/v2.9.9/logcli-linux-arm64.zip && \
    unzip logcli-linux-arm64.zip && \
    mv logcli-linux-arm64 /usr/local/bin/logcli

# Install s6-overlay (glibc, arm64)
ADD https://github.com/just-containers/s6-overlay/releases/latest/download/s6-overlay-noarch.tar.xz /tmp/
ADD https://github.com/just-containers/s6-overlay/releases/latest/download/s6-overlay-aarch64.tar.xz /tmp/
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay-aarch64.tar.xz && \
    rm -f /tmp/s6-overlay-*.tar.xz

# Configuration Files
COPY ./ /

# Entrypoint
ENTRYPOINT ["/init"]