[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cli"
version = "0.1.0"
description = "SlideRule command line tool"
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
sliderule-runner = "sliderule-runner.main:main"

[tool.setuptools.packages.find]
where = ["src"]