[build-system]
requires = ["setuptools>=68", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sliderule-cli"
dynamic = ["version"]
description = "SlideRule command line tool"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["sliderule", "boto3"]

[project.optional-dependencies]
progress = ["tqdm"]
recorder = ["geoip2", "pillow", "matplotlib"]

[project.scripts]
sliderule-cluster = "sliderule_cluster.main:main"
sliderule-provisioner = "sliderule_provisioner.main:main"
sliderule-recorder = "sliderule_recorder.main:main"
sliderule-runner = "sliderule_runner.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
root = "../.."