version: "3.9"
services:
  monitor:
    image: ${MONITOR_IMAGE}
    network_mode: "host"
    restart: always
    pull_policy: if_not_present
    entrypoint: /usr/local/etc/docker-entrypoint.sh
    stdin_open: true # docker run -i
    tty: true # docker run -t
    labels:
      - autoheal=true
  proxy:
    image: ${PROXY_IMAGE}
    network_mode: "host"
    restart: always
    pull_policy: if_not_present
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: /usr/local/etc/docker-entrypoint.sh
    volumes:
      - /etc/ssl/private:/etc/ssl/private
    environment:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - DOMAIN=$DOMAIN
      - REDIRECT_URI_SCHEME=https
    labels:
      - autoheal=true
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
