version: "3.9"
services:
  manager:
    image: ${MANAGER_IMAGE}
    network_mode: "host"
    restart: always
    pull_policy: if_not_present
    entrypoint: /docker-entrypoint.sh
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /data:/data
    environment:
      - MANAGER_SECRET_SALT=$MANAGER_SECRET_SALT
      - DUCKDB_LOCAL_FILE=$DUCKDB_LOCAL_FILE
      - DUCKDB_REMOTE_FILE=$DUCKDB_REMOTE_FILE
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
