AWSTemplateFormatVersion: '2010-09-09'
Description: SlideRule Cluster

Parameters:

  #
  # Variables
  #
  Version:
    Type: String
  EnvironmentVersion:
    Type: String
  IsPublic:
    Type: String
    AllowedValues:
      - "true"
      - "false"
  Domain:
    Type: String
  Cluster:
    Type: String
  ProjectBucket:
    Type: String
  ProjectFolder:
    Type: String
  ProjectPublicBucket:
    Type: String
  DestroyLambdaArn:
    Type: String
  ScheduleLambdaArn:
    Type: String
  ContainerRegistry:
    Type: String
  NodeCapacity:
    Type: Number
  TTL:
    Type: Number
  JwtIssuer:
    Type: String
  AlertStream:
    Type: String
  TelemetryStream:
    Type: String
  IlbUserData:
    Type: String
  MonitorUserData:
    Type: String
  NodeUserData:
    Type: String

  #
  # Constants
  #
  MonitorIP:
    Type: String
    Default: "10.0.1.4"
  IlbIP:
    Type: String
    Default: "10.0.128.5"
  AvailabilityZone:
    Type: String
    Default: "us-west-2d"
  PublicCIDRBlock:
    Type: String
    Default: "0.0.0.0/0"
  VpcCIDRBlock:
    Type: String
    Default: "10.0.0.0/16"
  InternetGatewayCIDRBlock:
    Type: String
    Default: "10.0.128.0/17"
  ClusterCIDRBlock:
    Type: String
    Default: "10.0.0.0/17"
  DockerComposeVersion:
    Type: String
    Default: "v2.24.5"

Conditions:

  HasAutoShutdown: !And
    - !Not [!Equals [!Ref ScheduleLambdaArn, ""]]
    - !Not [!Equals [!Ref DestroyLambdaArn, ""]]

Resources:

  #
  # Network
  #
  ClusterVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDRBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${Cluster}-vpc"
  # Internet Gateway (used by NAT Gateway and ILB)
  InternetGatewaySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ClusterVPC
      CidrBlock: !Ref InternetGatewayCIDRBlock
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Ref AvailabilityZone
  InternetGatewayRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ClusterVPC
  InternetGatewayRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttach
    Properties:
      RouteTableId: !Ref InternetGatewayRouteTable
      DestinationCidrBlock: !Ref PublicCIDRBlock
      GatewayId: !Ref InternetGateway
  InternetGatewayRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref InternetGatewaySubnet
      RouteTableId: !Ref InternetGatewayRouteTable
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  InternetGatewayAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref ClusterVPC
  # Private Subnet for Cluster
  ClusterSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ClusterVPC
      CidrBlock: !Ref ClusterCIDRBlock
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Ref AvailabilityZone
  ClusterRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ClusterVPC
  ClusterRoute:
    Type: AWS::EC2::Route
    DependsOn: ClusterNatGateway
    Properties:
      RouteTableId: !Ref ClusterRouteTable
      DestinationCidrBlock: !Ref PublicCIDRBlock
      NatGatewayId: !Ref ClusterNatGateway
  ClusterRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ClusterSubnet
      RouteTableId: !Ref ClusterRouteTable
  ClusterNatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  ClusterNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref InternetGatewaySubnet
      AllocationId: !GetAtt ClusterNatEIP.AllocationId
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref ClusterVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref ClusterRouteTable

  #
  # IAM Roles
  #
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
      Policies:
        - PolicyName: !Sub "${Cluster}-s3-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ["s3:ListBucket"]
                Resource:
                  - !Sub "arn:aws:s3:::${ProjectBucket}"
                  - !Sub "arn:aws:s3:::${ProjectPublicBucket}"
                  - arn:aws:s3:::pgc-opendata-dems
                  - arn:aws:s3:::prd-tnm
                  - arn:aws:s3:::esa-worldcover
                  - arn:aws:s3:::noaa-ocs-nationalbathymetry-pds
                  - arn:aws:s3:::dataforgood-fb-data
              - Effect: Allow
                Action: ["s3:GetObject"]
                Resource:
                  - !Sub "arn:aws:s3:::${ProjectBucket}/*"
                  - !Sub "arn:aws:s3:::${ProjectPublicBucket}/*"
                  - arn:aws:s3:::pgc-opendata-dems/*
                  - arn:aws:s3:::prd-tnm/*
                  - arn:aws:s3:::esa-worldcover/*
                  - arn:aws:s3:::noaa-ocs-nationalbathymetry-pds/*
                  - arn:aws:s3:::dataforgood-fb-data/*
              - Effect: Allow
                Action: ["s3:PutObject"]
                Resource:
                  - !Sub "arn:aws:s3:::${ProjectPublicBucket}/*"
        - PolicyName: !Sub "${Cluster}-ec2-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:TerminateInstances
                Resource: "*"
        - PolicyName: !Sub "${Cluster}-firehose-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecord
                  - firehose:PutRecordBatch
                Resource:
                  - !Sub "arn:aws:firehose:${AWS::Region}:${AWS::AccountId}:deliverystream/${AlertStream}"
                  - !Sub "arn:aws:firehose:${AWS::Region}:${AWS::AccountId}:deliverystream/${TelemetryStream}"
        - PolicyName: !Sub "${Cluster}-pubkey-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Domain}/*
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref ClusterRole]

  #
  # Security Group - Monitor
  #
  MonitorSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Monitor Security Group
      VpcId: !Ref ClusterVPC
      SecurityGroupIngress:
        # Loki (from Promtail)
        - IpProtocol: tcp
          FromPort: 3100
          ToPort: 3100
          CidrIp: !Ref VpcCIDRBlock
        # HAProxy (from internet)
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: !Ref VpcCIDRBlock
      SecurityGroupEgress:
        # ALL
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: !Ref PublicCIDRBlock
      Tags:
        - Key: Name
          Value: !Sub "${Cluster}-monitor-sg"

  #
  # Security Group - ILB
  #
  IlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ILB Security Group
      VpcId: !Ref ClusterVPC
      SecurityGroupIngress:
        # Public Internet
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref PublicCIDRBlock
        # Orchestrator (from HAProxy)
        - IpProtocol: tcp
          FromPort: 8050
          ToPort: 8050
          CidrIp: !Ref VpcCIDRBlock
        # Node Exporter (from Prometheus)
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: !Ref VpcCIDRBlock
      SecurityGroupEgress:
        # ALL
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: !Ref PublicCIDRBlock
      Tags:
        - Key: Name
          Value: !Sub "${Cluster}-ilb-sg"

  #
  # Security Group - Cluster
  #
  ClusterNodeSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Sliderule Cluster Security Group
      VpcId: !Ref ClusterVPC
      SecurityGroupIngress:
        # SlideRule (from HAProxy)
        - IpProtocol: tcp
          FromPort: 9081
          ToPort: 9081
          CidrIp: !Ref VpcCIDRBlock
        # Node Exporter (from Prometheus)
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: !Ref VpcCIDRBlock
      SecurityGroupEgress:
        # ALL
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: !Ref PublicCIDRBlock
      Tags:
        - Key: Name
          Value: !Sub "${Cluster}-sliderule-sg"

  #
  # EC2 Instance - ILB
  #
  IlbInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
      InstanceType: c8g.large
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: !Ref InstanceProfile
      SourceDestCheck: true
      Monitoring: false
      NetworkInterfaces:
        - DeviceIndex: 0
          PrivateIpAddress: !Ref IlbIP
          SubnetId: !Ref InternetGatewaySubnet
          AssociatePublicIpAddress: true
          GroupSet:
            - !Ref IlbSG
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: !Sub "${Cluster}-ilb"
        - Key: Version
          Value: !Ref Version
        - Key: IsPublic
          Value: !Ref IsPublic
        - Key: NodeCapacity
          Value: !Ref NodeCapacity
      UserData:
        Fn::Base64: !Ref IlbUserData

  #
  # EC2 Instance - Monitor
  #
  MonitorInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
      InstanceType: c8g.large
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: !Ref InstanceProfile
      SourceDestCheck: true
      Monitoring: false
      NetworkInterfaces:
        - DeviceIndex: 0
          PrivateIpAddress: !Ref MonitorIP
          SubnetId: !Ref ClusterSubnet
          GroupSet:
            - !Ref MonitorSG
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 40
            VolumeType: gp3
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: !Sub "${Cluster}-monitor"
      UserData:
        Fn::Base64: !Ref MonitorUserData

  #
  # Autoscaling Group - Cluster Node
  #
  NodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${Cluster}-lt"
      LaunchTemplateData:
        ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
        InstanceType: t4g.2xlarge
        IamInstanceProfile:
          Name: !Ref InstanceProfile
        NetworkInterfaces:
          - DeviceIndex: 0
            Groups:
              - !Ref ClusterNodeSG
        BlockDeviceMappings:
          - DeviceName: "/dev/xvda"
            Ebs:
              VolumeSize: 40
              VolumeType: gp3
              DeleteOnTermination: true
        UserData:
          Fn::Base64: !Ref NodeUserData

  NodeAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${Cluster}-asg"
      MinSize: !Ref NodeCapacity
      MaxSize: !Ref NodeCapacity
      DesiredCapacity: !Ref NodeCapacity
      VPCZoneIdentifier:
        - !Ref ClusterSubnet
      HealthCheckType: EC2
      CapacityRebalance: true
      LaunchTemplate:
        LaunchTemplateId: !Ref NodeLaunchTemplate
        Version: !GetAtt NodeLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: !Sub "${Cluster}-node"
          PropagateAtLaunch: true

  #
  # Auto-Shutdown
  #
  AutoShutdownCustomResource:
    Type: Custom::ScheduleStackDeletion
    Condition: HasAutoShutdown
    DependsOn:
      - NodeAutoScalingGroup
    Properties:
      ServiceToken: !Ref ScheduleLambdaArn
      StackName: !Ref AWS::StackName
      DeleteAfterMinutes: !Ref TTL
      DeletionLambdaArn: !Ref DestroyLambdaArn

  #
  # DNS
  #
  IlbRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${Domain}."   # ensure trailing dot or you can pass HostedZoneId instead
      Name: !Sub "${Cluster}.${Domain}"
      Type: A
      TTL: "300"
      ResourceRecords:
        - !GetAtt IlbInstance.PublicIp
