AWSTemplateFormatVersion: '2010-09-09'
Description: 'Kinesis Firehose with S3 delivery and Athena querying'

Parameters:

  ProjectBucket:
    Type: String
  AlertStream:
    Type: String
  TelemetryStream:
    Type: String

Resources:

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: FirehosePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:AbortMultipartUpload'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:ListBucketMultipartUploads'
                  - 's3:PutObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectBucket}'
                  - !Sub 'arn:aws:s3:::${ProjectBucket}/*'
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                  - 'lambda:GetFunctionConfiguration'
                Resource: "*"
              - Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/*:log-stream:*'

  #
  # Kinesis Firehose Alert Stream
  #
  AlertWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/kinesisfirehose/${AWS::StackName}-alert-stream'
      RetentionInDays: 7
  AlertCloudWatchLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref AlertWatchLogGroup
      LogStreamName: S3Delivery
  AlertFirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - FirehoseRole
    Properties:
      DeliveryStreamName: !Ref AlertStream
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub 'arn:aws:s3:::${ProjectBucket}'
        RoleARN: !GetAtt FirehoseRole.Arn
        Prefix: 'alerts/year=!{partitionKeyFromQuery:year}/month=!{partitionKeyFromQuery:month}/day=!{partitionKeyFromQuery:day}/'
        ErrorOutputPrefix: 'errors/alerts/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/!{firehose:error-output-type}/'
        BufferingHints:
          SizeInMBs: 64
          IntervalInSeconds: 300
        CompressionFormat: GZIP
        DynamicPartitioningConfiguration:
          Enabled: true
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: MetadataExtraction
              Parameters:
                - ParameterName: MetadataExtractionQuery
                  ParameterValue: '{year: .timestamp | strftime("%Y"), month: .timestamp | strftime("%m"), day: .timestamp | strftime("%d")}'
                - ParameterName: JsonParsingEngine
                  ParameterValue: JQ-1.6
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref AlertWatchLogGroup
          LogStreamName: !Ref AlertCloudWatchLogStream

  #
  # Kinesis Firehose Telemetry Stream
  #
  TelemetryWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/kinesisfirehose/${AWS::StackName}-telemetry-stream'
      RetentionInDays: 7
  TelemetryCloudWatchLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref TelemetryWatchLogGroup
      LogStreamName: S3Delivery
  TelemetryFirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - FirehoseRole
    Properties:
      DeliveryStreamName: !Ref TelemetryStream
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub 'arn:aws:s3:::${ProjectBucket}'
        RoleARN: !GetAtt FirehoseRole.Arn
        Prefix: 'telemetry/year=!{partitionKeyFromQuery:year}/month=!{partitionKeyFromQuery:month}/day=!{partitionKeyFromQuery:day}/'
        ErrorOutputPrefix: 'errors/telemetry/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/!{firehose:error-output-type}/'
        BufferingHints:
          SizeInMBs: 64
          IntervalInSeconds: 300
        CompressionFormat: GZIP
        DynamicPartitioningConfiguration:
          Enabled: true
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: MetadataExtraction
              Parameters:
                - ParameterName: MetadataExtractionQuery
                  ParameterValue: '{year: .timestamp | strftime("%Y"), month: .timestamp | strftime("%m"), day: .timestamp | strftime("%d")}'
                - ParameterName: JsonParsingEngine
                  ParameterValue: JQ-1.6
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref TelemetryWatchLogGroup
          LogStreamName: !Ref TelemetryCloudWatchLogStream

  #
  # Glue Database for Athena
  #
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${AWS::StackName}-database'
        Description: Database for telemetry and alert data

  #
  # Alert Table Definition
  #
  AlertTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: alerts
        Description: Alert messages from Kinesis Firehose
        TableType: EXTERNAL_TABLE
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string
        StorageDescriptor:
          Columns:
            - Name: timestamp
              Type: string
            - Name: code
              Type: int
            - Name: cluster
              Type: string
            - Name: version
              Type: string
            - Name: message
              Type: string
          Location: !Sub 's3://${ProjectBucket}/alerts/'
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          Compressed: true
          StoredAsSubDirectories: false
        Parameters:
          classification: json
          compressionType: gzip

  #
  # Telemetry Table Definition
  #
  TelemetryTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: telemetry
        Description: Telemetry messages from Kinesis Firehose
        TableType: EXTERNAL_TABLE
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string
        StorageDescriptor:
          Columns:
            - Name: timestamp
              Type: string
            - Name: source_ip
              Type: string
            - Name: aoi_x
              Type: double
            - Name: aoi_y
              Type: double
            - Name: client
              Type: string
            - Name: endpoint
              Type: string
            - Name: duration
              Type: double
            - Name: code
              Type: int
            - Name: account
              Type: string
            - Name: cluster
              Type: string
            - Name: version
              Type: string
          Location: !Sub 's3://${ProjectBucket}/telemetry/'
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          Compressed: true
          StoredAsSubDirectories: false
        Parameters:
          classification: json
          compressionType: gzip

  #
  # Athena WorkGroup
  #
  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub '${AWS::StackName}-workgroup'
      Description: WorkGroup for querying telemetry and alert data
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          OutputLocation: !Sub 's3://${ProjectBucket}/athena-results/'
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
