FROM amazonlinux:2023

# runtime dependencies
RUN dnf update -y \
    && dnf install -y \
        wget \
        gawk \
        gcc-c++ \
        make \
        cmake \
    && dnf clean all \
    && rm -rf /var/cache/yum

# install mamba for python based algorithms
RUN wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh \
    && bash Miniforge3-Linux-aarch64.sh -b

# install python dependencies for python based algorithms
COPY conda-linux-aarch64.lock .
RUN /root/miniforge3/bin/mamba create --copy -p /env --file conda-linux-aarch64.lock \
    && /root/miniforge3/bin/conda clean -afy
RUN /env/bin/pip install build

# install job runner script
COPY job_runner.py /

# entry point
ENTRYPOINT ["/env/bin/python", "job_runner.py"]
