{
 "title": "Logs by Level",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (count_over_time({job=\"sliderule\",level=~\"critical|error|warning|info|debug\"} [1m]))"
    }
   ]
  },
  {
   "title": "Critical Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"sliderule\",level=\"critical\"}"
    }
   ]
  },
  {
   "title": "Error and Warning Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"sliderule\",level=~\"error|warning\"}"
    }
   ]
  },
  {
   "title": "Info and Debug Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"sliderule\",level=~\"info|debug\"}"
    }
   ]
  }
 ]
}