{
 "title": "SlideRule Node Application Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(successful_request_count{job=\"analyzer_app\"}[1y])"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(failed_request_count{job=\"analyzer_app\"}[1y])"
    }
   ]
  },
  {
   "title": "Version Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(version_count{job=\"analyzer_app\"}[1y])"
    }
   ]
  },
  {
   "title": "Unique Originators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(unique_originators{job=\"analyzer_app\"}[1y])"
    }
   ]
  },
  {
   "title": "Blocked Originators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(blocked_originators{job=\"analyzer_app\"}[1y])"
    }
   ]
  },
  {
   "title": "Untracked Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(untracked_request_count{job=\"analyzer_app\"}[1y])"
    }
   ]
  },
  {
   "title": "DataFrame Endpoint Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(atl03x_count{job=\"analyzer_app\"} OR on() vector(0))"
    },
    {
     "expr": "(atl06x_count{job=\"analyzer_app\"} OR on() vector(0))"
    },
    {
     "expr": "(atl08x_count{job=\"analyzer_app\"} OR on() vector(0))"
    },
    {
     "expr": "(atl13x_count{job=\"analyzer_app\"} OR on() vector(0))"
    },
    {
     "expr": "(atl24x_count{job=\"analyzer_app\"} OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Proxied Endpoint Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "(atl03sp_count{job=\"analyzer_app\"} OR on() vector(0))",
     "legendFormat": "atl03sp"
    },
    {
     "expr": "(atl06p_count{job=\"analyzer_app\"} OR on() vector(0))",
     "legendFormat": "atl06p"
    },
    {
     "expr": "(atl08p_count{job=\"analyzer_app\"} OR on() vector(0))",
     "legendFormat": "atl08p"
    },
    {
     "expr": "(gedi01bp_count{job=\"analyzer_app\"} OR on() vector(0))",
     "legendFormat": "gedi01bp"
    },
    {
     "expr": "(gedi02ap_count{job=\"analyzer_app\"} OR on() vector(0))",
     "legendFormat": "gedi02ap"
    },
    {
     "expr": "(gedi04ap_count{job=\"analyzer_app\"} OR on() vector(0))",
     "legendFormat": "gedi04ap"
    },
    {
     "expr": "(h5p_count{job=\"analyzer_app\"} OR on() vector(0))",
     "legendFormat": "h5p"
    }
   ]
  },
  {
   "title": "DataFrame Endpoint Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(atl03x_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "atl03x"
    },
    {
     "expr": "rate(atl06x_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "atl06x"
    },
    {
     "expr": "rate(atl08x_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "atl08x"
    },
    {
     "expr": "rate(atl13x_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "atl13x"
    },
    {
     "expr": "rate(atl24x_count{job=\"analyzer_app\"}[1m])  ",
     "legendFormat": "atl24x"
    }
   ]
  },
  {
   "title": "Proxied Endpoint Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(atl03sp_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "atl03sp"
    },
    {
     "expr": "rate(atl06p_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "atl06p"
    },
    {
     "expr": "rate(atl08p_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "atl08p"
    },
    {
     "expr": "rate(gedi01bp_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "gedi01bp"
    },
    {
     "expr": "rate(gedi02ap_count{job=\"analyzer_app\"}[1m])",
     "legendFormat": "gedi02ap"
    },
    {
     "expr": "rate(gedi04ap_count{job=\"analyzer_app\"}[1m])  ",
     "legendFormat": "gedi04ap"
    },
    {
     "expr": "rate(h5p_count{job=\"analyzer_app\"}[1m]) ",
     "legendFormat": "h5p"
    }
   ]
  }
 ]
}