{
 "title": "Orchestrator Application Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Service Discovery Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "num_requests{job=\"orchestrator_app\"}"
    },
    {
     "expr": "num_complete{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "Service Discovery Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "num_failures{job=\"orchestrator_app\"}"
    },
    {
     "expr": "num_timeouts{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "Active Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "num_active_locks{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "Nodes Registered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sliderule_members{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "Service Discovery Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(num_requests{job=\"orchestrator_app\"}[1m])"
    }
   ]
  },
  {
   "title": "Member Startups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "num_startups{job=\"orchestrator_app\"}"
    }
   ]
  }
 ]
}