{
 "title": "SlideRule Node Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "max atl03s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(atl03s{job=\"orchestrator_app\"}[1y])"
    }
   ]
  },
  {
   "title": "max atl06",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(atl06{job=\"orchestrator_app\"}[1y])"
    }
   ]
  },
  {
   "title": "max atl08",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(atl08{job=\"orchestrator_app\"}[1y])"
    }
   ]
  },
  {
   "title": "max atl03sp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(atl03sp{job=\"orchestrator_app\"}[1y])"
    }
   ]
  },
  {
   "title": "max atl06p",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(atl06p{job=\"orchestrator_app\"}[1y])"
    }
   ]
  },
  {
   "title": "max atl08p",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(atl08p{job=\"orchestrator_app\"}[1y])"
    }
   ]
  },
  {
   "title": "total atl03 granules",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atl03s_count{job=\"orchestrator_app\"} + atl06_count{job=\"orchestrator_app\"} + atl08_count{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "total icesat2 proxied requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atl03sp_count{job=\"orchestrator_app\"} + atl06p_count{job=\"orchestrator_app\"} + atl08p_count{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "total gedi proxied requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gedi01bp_count{job=\"orchestrator_app\"} + gedi02ap_count{job=\"orchestrator_app\"} + gedi04ap_count{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "total gedi granules",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gedi01b_count{job=\"orchestrator_app\"} + gedi02a_count{job=\"orchestrator_app\"} + gedi04a_count{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "total version requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "version_count{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "total raster requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "samples_count{job=\"orchestrator_app\"} + subsets_count{job=\"orchestrator_app\"}"
    }
   ]
  },
  {
   "title": "Endpoint Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "atl03s_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl03s"
    },
    {
     "expr": "atl06_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl06"
    },
    {
     "expr": "atl08_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl08"
    },
    {
     "expr": "gedi01b_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi01b"
    },
    {
     "expr": "gedi02a_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi02a"
    },
    {
     "expr": "gedi04a_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi04a"
    },
    {
     "expr": "h5_count{job=\"orchestrator_app\"}",
     "legendFormat": "h5"
    }
   ]
  },
  {
   "title": "Proxied Endpoint Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "atl03sp_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl03sp"
    },
    {
     "expr": "atl06p_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl06p"
    },
    {
     "expr": "atl08p_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl08p"
    },
    {
     "expr": "gedi01bp_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi01bp"
    },
    {
     "expr": "gedi02ap_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi02ap"
    },
    {
     "expr": "gedi04ap_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi04ap"
    },
    {
     "expr": "h5p_count{job=\"orchestrator_app\"}",
     "legendFormat": "h5p"
    }
   ]
  },
  {
   "title": "Endpoint Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(atl03s_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "atl03s"
    },
    {
     "expr": "rate(atl06_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "atl06"
    },
    {
     "expr": "rate(atl08_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "atl08"
    },
    {
     "expr": "rate(gedi01b_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "gedi01b"
    },
    {
     "expr": "rate(gedi02a_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "gedi02a"
    },
    {
     "expr": "rate(gedi04a_count{job=\"orchestrator_app\"}[1m])  ",
     "legendFormat": "gedi04a"
    },
    {
     "expr": "rate(h5_count{job=\"orchestrator_app\"}[1m])  ",
     "legendFormat": "h5"
    }
   ]
  },
  {
   "title": "Proxied Endpoint Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(atl03sp_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "atl03sp"
    },
    {
     "expr": "rate(atl06p_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "atl06p"
    },
    {
     "expr": "rate(atl08p_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "atl08p"
    },
    {
     "expr": "rate(gedi01bp_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "gedi01bp"
    },
    {
     "expr": "rate(gedi02ap_count{job=\"orchestrator_app\"}[1m])",
     "legendFormat": "gedi02ap"
    },
    {
     "expr": "rate(gedi04ap_count{job=\"orchestrator_app\"}[1m])  ",
     "legendFormat": "gedi04ap"
    },
    {
     "expr": "rate(h5p_count{job=\"orchestrator_app\"}[1m]) ",
     "legendFormat": "h5p"
    }
   ]
  },
  {
   "title": "atl03s durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "atl03s{job=\"orchestrator_app\"}",
     "legendFormat": "atl03s-sampled"
    },
    {
     "expr": "atl03s_sum{job=\"orchestrator_app\"} / atl03s_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl03s-average"
    }
   ]
  },
  {
   "title": "atl03sp durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "atl03sp{job=\"orchestrator_app\"}",
     "legendFormat": "atl03sp-sampled"
    },
    {
     "expr": "atl03sp_sum{job=\"orchestrator_app\"} / atl03sp_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl03sp-average"
    }
   ]
  },
  {
   "title": "atl06 durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "atl06{job=\"orchestrator_app\"}",
     "legendFormat": "atl06-sampled"
    },
    {
     "expr": "atl06_sum{job=\"orchestrator_app\"} / atl06_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl06-average"
    }
   ]
  },
  {
   "title": "atl06p durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "atl06p{job=\"orchestrator_app\"}",
     "legendFormat": "atl06p-sampled"
    },
    {
     "expr": "atl06p_sum{job=\"orchestrator_app\"} / atl06p_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl06p-average"
    }
   ]
  },
  {
   "title": "atl08 durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "atl08{job=\"orchestrator_app\"}",
     "legendFormat": "atl08-sampled"
    },
    {
     "expr": "atl08_sum{job=\"orchestrator_app\"} / atl08_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl08-average"
    }
   ]
  },
  {
   "title": "atl08p durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "atl08p{job=\"orchestrator_app\"}",
     "legendFormat": "atl08p-sampled"
    },
    {
     "expr": "atl08p_sum{job=\"orchestrator_app\"} / atl08p_count{job=\"orchestrator_app\"}",
     "legendFormat": "atl08p-average"
    }
   ]
  },
  {
   "title": "gedi durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "gedi01b{job=\"orchestrator_app\"}",
     "legendFormat": "gedi01b-sampled"
    },
    {
     "expr": "gedi01b_sum{job=\"orchestrator_app\"} / gedi01b_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi01b-average"
    },
    {
     "expr": "gedi02a{job=\"orchestrator_app\"}",
     "legendFormat": "gedi02a-sampled"
    },
    {
     "expr": "gedi02a_sum{job=\"orchestrator_app\"} / gedi02a_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi02a-average"
    },
    {
     "expr": "gedi04a{job=\"orchestrator_app\"}",
     "legendFormat": "gedi04a-sampled"
    },
    {
     "expr": "gedi04a_sum{job=\"orchestrator_app\"} / gedi04a_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi04a-average"
    }
   ]
  },
  {
   "title": "gedi[p] durations (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "gedi01bp{job=\"orchestrator_app\"}",
     "legendFormat": "gedi01bp-sampled"
    },
    {
     "expr": "gedi01bp_sum{job=\"orchestrator_app\"} / gedi01bp_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi01bp-average"
    },
    {
     "expr": "gedi02ap{job=\"orchestrator_app\"}",
     "legendFormat": "gedi02ap-sampled"
    },
    {
     "expr": "gedi02ap_sum{job=\"orchestrator_app\"} / gedi02ap_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi02ap-average"
    },
    {
     "expr": "gedi04ap{job=\"orchestrator_app\"}",
     "legendFormat": "gedi04ap-sampled"
    },
    {
     "expr": "gedi04ap_sum{job=\"orchestrator_app\"} / gedi04ap_count{job=\"orchestrator_app\"}",
     "legendFormat": "gedi04ap-average"
    }
   ]
  }
 ]
}