{
 "title": "SlideRule System Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - node_boot_time_seconds{job=\"sliderule_sys\"})"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"sliderule_sys\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.00 - avg(irate(node_cpu_seconds_total{job=\"sliderule_sys\",mode=\"idle\"}[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"sliderule_sys\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{job=\"sliderule_sys\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total Network Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"sliderule_sys\"}[1m])"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"sliderule_sys\"}[1m])"
    }
   ]
  },
  {
   "title": "Network Outbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens5\",job=\"sliderule_sys\"}[1m])"
    }
   ]
  },
  {
   "title": "Network Inbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\",job=\"sliderule_sys\"}[1m])"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\",job=\"sliderule_sys\"}"
    }
   ]
  },
  {
   "title": "Accumulated Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_disk_io_time_seconds_total{device=\"nvme0n1\",job=\"sliderule_sys\"}"
    }
   ]
  }
 ]
}