{
 "title": "Orchestrator",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Service Discovery Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "num_requests{job=\"orchestrator\"}"
    }
   ]
  },
  {
   "title": "Service Discovery Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "num_failures{job=\"orchestrator\"}"
    }
   ]
  },
  {
   "title": "Service Discovery Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(num_requests{job=\"orchestrator\"}[1m])"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "num_unique_visitors{job=\"orchestrator\"}"
    }
   ]
  }
 ]
}