{
 "title": "SlideRule Proxy Application Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Endpoint Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(SourceEndpoint_atl03s_hits{}[1m]))",
     "legendFormat": "atl03s"
    },
    {
     "expr": "sum by (job) (rate(SourceEndpoint_atl06_hits{}[1m]))",
     "legendFormat": "atl06"
    },
    {
     "expr": "sum by (job) (rate(SourceEndpoint_definition_hits{}[1m]))",
     "legendFormat": "definition"
    },
    {
     "expr": "sum by (job) (rate(SourceEndpoint_h5_hits{}[1m]))",
     "legendFormat": "h5"
    },
    {
     "expr": "sum by (job) (rate(SourceEndpoint_h5p_hits{}[1m]))",
     "legendFormat": "h5p"
    }
   ]
  },
  {
   "title": "Request Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(HttpServer_duration{job=\"sliderule_proxy_app\"}[1m])"
    }
   ]
  },
  {
   "title": "Request Regions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (job) (icesat2_alaska_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Alaska"
    },
    {
     "expr": "sum by (job) (icesat2_canada_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Canada"
    },
    {
     "expr": "sum by (job) (icesat2_greenland_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Greenland"
    },
    {
     "expr": "sum by (job) (icesat2_continental_us_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Continental US"
    },
    {
     "expr": "sum by (job) (icesat2_central_america_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Central America"
    },
    {
     "expr": "sum by (job) (icesat2_south_america_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "South America"
    },
    {
     "expr": "sum by (job) (icesat2_africa_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Africa"
    },
    {
     "expr": "sum by (job) (icesat2_middle_east_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Middle East"
    },
    {
     "expr": "sum by (job) (icesat2_europe_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Europe"
    },
    {
     "expr": "sum by (job) (icesat2_north_asia_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "North Asia"
    },
    {
     "expr": "sum by (job) (icesat2_south_asia_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "South Asia"
    },
    {
     "expr": "sum by (job) (icesat2_oceania_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Oceania"
    },
    {
     "expr": "sum by (job) (icesat2_antarctica_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Antarctica"
    },
    {
     "expr": "sum by (job) (icesat2_unknown_region_hits{job=\"sliderule_proxy_app\"})",
     "legendFormat": "Unknown"
    }
   ]
  }
 ]
}