{
 "title": "Monitor System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"manager\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.00 - avg(irate(node_cpu_seconds_total{job=\"manager\",mode=\"idle\"}[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\",job=\"manager\"}"
    }
   ]
  }
 ]
}