[pytest]
pythonpath = .
env =
    DOMAIN=localhost
    AUTHENTICATOR_HOSTNAME=localhost
    GITHUB_ORG=myorg
    GITHUB_CLIENT_SECRET_NAME=testsliderule.org/github-oauth-client
    HMAC_SIGNING_KEY_ARN=testsliderule.org/github-oauth-hmac-key
    ALLOWED_REDIRECT_HOSTS=localhost
    SESSION_TABLE=authenticator-testsliderule-store
    GITHUB_AUTHORIZE_URL=http://localhost:9083/login/oauth/authorize
    GITHUB_TOKEN_URL=http://localhost:9083/login/oauth/access_token
    GITHUB_DEVICE_CODE_URL=http://localhost:9083/login/device/code
    GITHUB_API_URL=http://localhost:9083/api
