# conda env create -f environment.yml
name: provisioner
channels:
  - conda-forge
dependencies:
  - boto3
  - coverage
  - croniter
  - cryptography
  - pytest
  - pytest-env
  - requests
  - sliderule
  - pip