name: Manager Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 22 * * 5' # Every Sunday at 10 pm

jobs:
  test:
    name: manager-test
    runs-on: ubuntu-latest
    env:
      DUCKDB_ALREADY_INSTALLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Cache conda environment
      #   uses: actions/cache@v4
      #   env:
      #     CACHE_NUMBER: 1
      #   with:
      #     path: ~/conda_pkgs_dir
      #     key: >
      #       ${{ format('{0}-conda-{1}-{2}',
      #         runner.os,
      #         env.CACHE_NUMBER,
      #         hashFiles('targets/slideruleearth-aws/docker/manager/environment.yml')) }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: manager
          environment-file: targets/slideruleearth-aws/docker/manager/environment.yml
          use-only-tar-bz2: false

      - name: Download and install DuckDB spatial extension
        shell: bash -l {0}
        run: |
          EXT=$(python -c "import duckdb; print(duckdb.__version__)")
          PLATFORM="linux_amd64"
          EXT_DIR="$HOME/.duckdb/extensions/v${EXT}/${PLATFORM}"
          mkdir -p "${EXT_DIR}"
          printf "Downloading spatial extension to ${EXT_DIR}"

          curl -L "https://extensions.duckdb.org/v${EXT}/${PLATFORM}/spatial.duckdb_extension.gz" \
            | gunzip -c > "${EXT_DIR}/spatial.duckdb_extension"

      - name: Download MaxMind GeoLite2 databases
        shell: bash -l {0}
        run: |
          sudo mkdir -p /data
          sudo chmod 777 /data
          curl -L -o /data/GeoLite2-Country.mmdb "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb"
          curl -L -o /data/GeoLite2-City.mmdb "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb"
          curl -L -o /data/GeoLite2-ASN.mmdb "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb"

      - name: Initialize manager database
        shell: bash -l {0}
        working-directory: targets/slideruleearth-aws/docker/manager
        run: |
          # Build the DuckDB database
          make init

      - name: Run manager tests with coverage
        shell: bash -l {0}
        working-directory: targets/slideruleearth-aws/docker/manager
        run: |
          make test
