# This workflow will publish the Node.js package to npm when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to npm

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      working-directory: clients/nodejs/sliderule
      run: npm ci

    - name: Build and publish
      working-directory: clients/nodejs
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: make publish
