# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: Self Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 22 * * 5' # Every Sunday at 10 pm


jobs:
  self_test:
    name: Sliderule regression test
    runs-on: ubuntu-latest
    container: ghcr.io/slideruleearth/sliderule-buildenv:latest

    steps:
    - name: Checkout CoastNet
      uses: actions/checkout@v3
      with:
        repository: SlideRuleEarth/ut-ATL24-coastnet
        path: ut-ATL24-coastnet

    - name: Checkout Qtrees
      uses: actions/checkout@v3
      with:
        repository: SlideRuleEarth/ut-ATL24-qtrees
        path: ut-ATL24-qtrees

    - name: Checkout OpenOceans++
      uses: actions/checkout@v3
      with:
        repository: SlideRuleEarth/ut-ATL24-oopp
        path: ut-ATL24-oopp

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: sliderule

    - name: Build sliderule
      run: |
       cd sliderule/targets/slideruleearth-aws
       make config-debug
       make

    - name: Run test
      run: |
       cd sliderule/targets/slideruleearth-aws
       make selftest TEST=../../targets/slideruleearth-aws/test_runner.lua
